In [1]:
import numpy as np
import pandas as pd

In [2]:
ds = pd.read_csv("Prostate_Cancer.csv")
ds.head()

,id,diagnosis_result,radius,texture,perimeter,area,smoothness,compactness,symmetry,fractal_dimension
0,1,M,23,12,151,954,0.143,0.278,0.242,0.079
1,2,B,9,13,133,1326,0.143,0.079,0.181,0.057
2,3,M,21,27,130,1203,0.125,0.160,0.207,0.060
3,4,M,14,16,78,386,0.070,0.284,0.260,0.097
4,5,M,9,19,135,1297,0.141,0.133,0.181,0.059

In [12]:
X = ds.iloc[:, 2:]

In [13]:
X.head()

,radius,texture,perimeter,area,smoothness,compactness,symmetry,fractal_dimension
0,23,12,151,954,0.143,0.278,0.242,0.079
1,9,13,133,1326,0.143,0.079,0.181,0.057
2,21,27,130,1203,0.125,0.160,0.207,0.060
3,14,16,78,386,0.070,0.284,0.260,0.097
4,9,19,135,1297,0.141,0.133,0.181,0.059

In [14]:
y = ds.iloc[:, 1]

In [15]:
y.head()

0    M
1    B
2    M
3    M
4    M
Name: diagnosis_result, dtype: object

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
from sklearn.ensemble import RandomForestClassifier

In [19]:
rf = RandomForestClassifier()

In [28]:
param_grid = [{
    'n_estimators': [500, 1000, 1500],
    'criterion': ['entropy', 'gini'],
    'min_samples_split': [5, 10, 15],
    'min_samples_leaf': [1, 2, 4],
    'max_depth': [10, 20, 30]
}]

In [21]:
from sklearn.model_selection import GridSearchCV

In [29]:
gs = GridSearchCV(
    rf,
    param_grid,
    scoring='accuracy',
    n_jobs=-1,
    cv=2
)

In [30]:
gs.fit(X_train, y_train)

GridSearchCV(cv=2, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid=[{'criterion': ['entropy', 'gini'],
                          'max_depth': [10, 20, 30],
                          'min_samples_leaf': [1, 2, 4],
                          'min_samples_split': [5, 10, 15],
                          'n_estimators': [500, 1000, 1500]}],
             scoring='accuracy')

In [31]:
gs.best_score_

np.float64(0.9125000000000001)

In [32]:
gs.best_params_

{'criterion': 'gini',
 'max_depth': 20,
 'min_samples_leaf': 2,
 'min_samples_split': 15,
 'n_estimators': 1000}

In [33]:
gs.cv_results_

{'mean_fit_time': array([0.99124122, 1.97884429, 3.1858629 , 1.07678092, 1.97562611,
        3.06947601, 1.05408776, 2.23300993, 2.77171588, 0.93597913,
        2.03211033, 2.81843936, 0.92953265, 2.03177452, 3.2923826 ,
        0.95721984, 2.00705159, 2.78826773, 0.92556024, 2.0295155 ,
        2.7971853 , 0.93611884, 2.01727164, 3.23119748, 0.92980623,
        2.0068866 , 2.80830669, 0.94085741, 1.87655473, 2.82865608,
        1.02039385, 1.88595569, 3.03010893, 1.06386304, 1.94088995,
        2.83016086, 0.99354649, 2.04889834, 2.83222163, 1.05539167,
        2.0195272 , 2.82035148, 1.04154766, 2.02419937, 2.82004547,
        1.07575512, 2.08024251, 3.24658215, 1.19223571, 2.73365724,
        3.84414089, 1.29589987, 3.15890384, 4.84087777, 1.60211563,
        2.93074286, 4.49645817, 1.34367251, 3.02383459, 3.92327094,
        1.27529681, 3.06947315, 4.17483854, 1.34730434, 3.10542858,
        4.68064964, 1.53458571, 2.71481717, 4.35249865, 1.31804442,
        2.65564084, 4.05890489, 1.51896453, 2.61650348, 4.12954819,
        1.75455177, 3.5789814 , 4.24763906, 1.39184213, 3.59257531,
        4.26760423, 1.47613919, 3.28715944, 5.37321031, 1.43491709,
        2.61299789, 3.9651562 , 1.5014323 , 2.56756771, 3.99534249,
        1.48442245, 3.15617895, 4.13266814, 1.51998925, 3.00429273,
        4.46760702, 1.46479201, 3.16134346, 4.60123765, 1.56141853,
        3.2178607 , 4.1543833 , 1.41385031, 3.21719038, 4.31739426,
        1.53601146, 3.23238981, 4.62172163, 1.55106783, 3.16263533,
        4.39630282, 1.29986537, 2.53722155, 3.92797792, 1.4309411 ,
        2.54239249, 4.63457465, 1.44810903, 2.71798527, 4.03932226,
        1.67762101, 2.66159678, 4.70920551, 1.32468295, 3.49241245,
        4.04282176, 1.45772135, 3.14896929, 4.07877731, 1.33083141,
        3.09387231, 4.53526163, 1.41044283, 3.183586  , 4.32664418,
        1.28648555, 2.54410028, 3.77092862, 1.42591798, 2.49362421,
        3.74859726, 1.40827668, 3.07361257, 3.76654756, 1.39140856,
        2.82366192, 3.82992566, 1.45454681, 3.22958207, 3.82923901,
        1.30193686, 2.99992824, 4.60333562, 1.30983984, 2.8601563 ,
        5.21980691, 1.75920796, 3.39771116, 5.4719075 , 1.47780025,
        3.88790202, 4.27654803]),
 'std_fit_time': array([9.71794128e-04, 1.76894665e-03, 1.24152064e-01, 9.26212072e-02,
        1.29038095e-02, 9.78215933e-02, 7.06878901e-02, 3.71420383e-03,
        5.70797920e-03, 5.45835495e-03, 1.44048810e-01, 9.78624821e-03,
        7.27236271e-03, 1.53854132e-01, 1.49706602e-02, 8.80002975e-04,
        1.23566031e-01, 1.62452459e-02, 6.05010986e-03, 1.47887468e-01,
        4.64570522e-03, 4.79531288e-03, 1.35508418e-01, 6.47604465e-03,
        5.45382500e-03, 1.24681830e-01, 5.69264889e-02, 1.54628754e-02,
        1.25298500e-02, 1.60123110e-02, 7.17062950e-02, 1.14667416e-03,
        2.10674286e-01, 1.87599659e-02, 1.02624297e-01, 6.91366196e-03,
        6.52904510e-02, 1.34585738e-01, 1.05866194e-02, 1.07914090e-01,
        1.25955820e-01, 1.00203753e-02, 1.04566813e-02, 1.60979629e-01,
        1.90036297e-02, 3.08132172e-03, 1.67782426e-01, 3.42766047e-02,
        1.60143375e-02, 4.66701388e-01, 5.32778502e-02, 1.53362751e-02,
        3.54964972e-01, 4.20079231e-01, 1.37386799e-01, 1.03926778e-01,
        4.34296966e-01, 1.87635422e-04, 4.08466220e-01, 3.05438042e-03,
        1.64115429e-03, 2.10311532e-01, 1.90448761e-01, 2.84450054e-02,
        4.72944379e-01, 1.03026509e-01, 2.20232487e-01, 2.89601088e-02,
        3.68239045e-01, 2.19721794e-02, 2.69148350e-02, 1.04180574e-01,
        1.91372871e-01, 7.62319565e-03, 6.17026091e-02, 2.47133970e-02,
        7.13624954e-02, 1.51101351e-02, 1.09839439e-03, 2.15692759e-01,
        4.59825993e-03, 9.08970833e-04, 3.22655201e-01, 6.93100691e-02,
        7.89868832e-03, 2.91320086e-02, 1.43843889e-02, 1.84974790e-01,
        3.23045254e-03, 7.16295242e-02, 1.75424337e-01, 1.13963366e-01,
        5.04862070e-02, 1.90541983e-01, 1.13759279e-01, 2.76681900e-01,
        5.78711033e-02, 3.20168376e-01, 3.84349942e-01, 2.00667858e-01,
        3.25580120e-01, 4.20478582e-02, 1.32123232e-01, 4.23039556e-01,
        3.32317352e-02, 2.07302809e-01, 3.94841313e-01, 8.67761374e-02,
        1.09918118e-02, 3.13745737e-01, 4.78947759e-01, 4.05396223e-02,
        2.24019289e-02, 7.31836557e-02, 1.65360928e-01, 2.00817585e-02,
        3.16619873e-01, 1.87104821e-01, 2.43138075e-02, 5.86038828e-02,
        5.97119331e-04, 9.96446609e-03, 5.39134145e-01, 2.84392834e-02,
        7.48182535e-02, 3.49386930e-02, 2.31677294e-02, 4.00198579e-01,
        4.99758720e-02, 1.97554827e-02, 3.84608746e-01, 5.40832520e-01,
        1.70421600e-03, 1.77410483e-01, 5.19865274e-01, 1.75057650e-02,
        1.71432495e-02, 1.13654137e-03, 1.63263917e-01, 3.21960449e-03,
        1.78378820e-02, 1.41723275e-01, 1.59813166e-02, 1.45221949e-02,
        1.48399234e-01, 2.93055177e-01, 1.09347105e-02, 1.87672973e-01,
        3.25324535e-02, 3.20541859e-03, 1.58841610e-02, 4.21246529e-01,
        5.55517197e-01, 6.05142117e-03, 1.58358574e-01, 8.22464228e-01,
        3.69528532e-01, 4.84175801e-01, 3.23480487e-01, 2.82787085e-02,
        7.48128891e-02, 2.14055181e-01]),
 'mean_score_time': array([0.05329895, 0.10770571, 0.14779043, 0.06232107, 0.10367131,
        0.15246892, 0.05044067, 0.09103525, 0.15264344, 0.05304849,
        0.10078704, 0.15435302, 0.05197573, 0.09930015, 0.14404869,
        0.05270112, 0.10657704, 0.15141022, 0.05326748, 0.09521425,
        0.14812338, 0.05359375, 0.09696293, 0.1411134 , 0.05199587,
        0.09873676, 0.14794314, 0.05257297, 0.10165071, 0.14991391,
        0.05108237, 0.10181689, 0.14642501, 0.04812443, 0.09452844,
        0.14837742, 0.05047941, 0.09694803, 0.15381312, 0.05180955,
        0.09905553, 0.15253603, 0.04834843, 0.0994575 , 0.19018745,
        0.04757285, 0.13834381, 0.21053183, 0.07553291, 0.14802861,
        0.21023679, 0.08116603, 0.14637125, 0.21441388, 0.09480762,
        0.14689922, 0.20956242, 0.07227397, 0.1445564 , 0.20229077,
        0.0726341 , 0.14260519, 0.22606885, 0.07106435, 0.16171229,
        0.22441828, 0.07765102, 0.14143455, 0.21948934, 0.07385218,
        0.13917089, 0.21250987, 0.07242811, 0.15031922, 0.23768771,
        0.07913458, 0.19294012, 0.22790205, 0.0767076 , 0.14991999,
        0.23934996, 0.07722437, 0.1625638 , 0.22953284, 0.07419097,
        0.14082682, 0.20461035, 0.08899105, 0.13681686, 0.22126651,
        0.08335865, 0.15006292, 0.21982658, 0.07564008, 0.15556669,
        0.2054956 , 0.07666147, 0.14181542, 0.21711266, 0.06988597,
        0.15371108, 0.23093688, 0.07375658, 0.17374372, 0.21262097,
        0.0734427 , 0.14322627, 0.20570326, 0.07607698, 0.14591885,
        0.20335782, 0.07215154, 0.14219677, 0.21006906, 0.07271945,
        0.1479615 , 0.2005167 , 0.07654881, 0.15361094, 0.22245336,
        0.08171988, 0.13414764, 0.2239002 , 0.07012367, 0.14166546,
        0.25779402, 0.08147764, 0.16385925, 0.2097255 , 0.07372987,
        0.14066541, 0.20486629, 0.08123255, 0.13398266, 0.20362329,
        0.07266641, 0.13573909, 0.20060909, 0.07048488, 0.13468945,
        0.20410895, 0.07136822, 0.1385752 , 0.20165908, 0.07236195,
        0.13754773, 0.20628405, 0.07185495, 0.14852858, 0.20894897,
        0.07528281, 0.16611373, 0.25697899, 0.07001925, 0.16932178,
        0.29153407, 0.09706604, 0.18168986, 0.11584306, 0.08489668,
        0.15119755, 0.07432353]),
 'std_score_time': array([7.20262527e-04, 6.95860386e-03, 1.35350227e-03, 1.00673437e-02,
        9.77516174e-04, 6.10446930e-03, 3.05259228e-03, 2.71332264e-03,
        2.91085243e-03, 3.30805779e-04, 3.85534763e-03, 1.17862225e-03,
        4.60147858e-04, 4.06455994e-03, 3.23677063e-03, 3.98516655e-04,
        4.55439091e-03, 3.03804874e-03, 5.52654266e-04, 6.73377514e-03,
        2.09212303e-04, 3.01718712e-04, 4.55808640e-03, 1.54983997e-03,
        3.78489494e-04, 3.30758095e-03, 5.61118126e-04, 2.69174576e-04,
        6.19888306e-04, 4.00185585e-04, 3.10039520e-03, 1.05309486e-03,
        7.86352158e-03, 5.97357750e-04, 6.36029243e-03, 2.77996063e-04,
        9.74893570e-04, 4.88507748e-03, 4.27532196e-03, 8.73088837e-04,
        4.29177284e-03, 2.63941288e-03, 1.91950798e-03, 2.72727013e-03,
        1.23000145e-03, 1.21617317e-03, 1.46899223e-02, 6.77466393e-04,
        5.77211380e-04, 7.19809532e-03, 5.55753708e-03, 1.21753216e-02,
        5.66613674e-03, 5.48171997e-03, 3.86238098e-05, 1.15776062e-02,
        1.13499165e-03, 1.33728981e-03, 8.39054585e-03, 4.31346893e-03,
        2.24173069e-03, 4.23276424e-03, 1.86382532e-02, 1.63674355e-04,
        9.78887081e-03, 1.83689594e-03, 1.75523758e-03, 6.32679462e-03,
        2.14571953e-02, 2.88355350e-03, 6.36816025e-04, 5.96261024e-03,
        1.15001202e-03, 1.16697550e-02, 3.01635265e-03, 1.74343586e-03,
        2.76935101e-03, 1.56079531e-02, 2.02298164e-03, 4.02379036e-03,
        5.01668453e-03, 5.82730770e-03, 1.92651749e-02, 1.71331167e-02,
        3.50630283e-03, 5.58257103e-04, 5.82361221e-03, 2.03286409e-02,
        1.36017799e-04, 1.61900520e-02, 6.64007664e-03, 8.97800922e-03,
        4.08208370e-03, 7.61389732e-04, 5.83410263e-04, 6.50835037e-03,
        6.35981560e-04, 5.36942482e-03, 7.03442097e-03, 2.04324722e-04,
        1.05097294e-02, 7.58278370e-03, 4.22835350e-04, 1.45149231e-02,
        5.24091721e-03, 2.89821625e-03, 7.21681118e-03, 2.39300728e-03,
        1.91187859e-03, 6.27303123e-03, 9.89437103e-06, 2.29871273e-03,
        2.52115726e-03, 4.30345535e-05, 2.03835964e-03, 2.40719318e-03,
        2.29263306e-03, 6.05010986e-03, 1.21788979e-02, 2.62794495e-02,
        8.43119621e-03, 1.64198875e-03, 8.91721249e-03, 7.34329224e-05,
        1.10411644e-03, 7.07376003e-03, 7.27415085e-03, 2.63437033e-02,
        9.72068310e-03, 2.94220448e-03, 1.72364712e-03, 3.99351120e-05,
        2.21967697e-04, 7.60555267e-04, 1.88112259e-03, 6.30140305e-04,
        4.04357910e-04, 1.44398212e-03, 1.61647797e-04, 1.30474567e-03,
        1.25002861e-03, 1.45816803e-03, 2.10058689e-03, 7.39216805e-04,
        1.86109543e-03, 3.09324265e-03, 4.27770615e-03, 1.67858601e-03,
        1.28395557e-02, 8.46278667e-03, 4.10771370e-03, 3.07766199e-02,
        2.37281322e-02, 1.95741653e-04, 6.85477257e-03, 1.65482759e-02,
        2.05329657e-02, 1.02611780e-02, 7.80677795e-03, 1.22138262e-02,
        9.51731205e-03, 1.24737024e-02]),
 'param_criterion': masked_array(data=['entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_max_depth': masked_array(data=[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
                    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 20,
                    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
                    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 30, 30,
                    30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
                    30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 10, 10,
                    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
                    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 20, 20, 20, 20,
                    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
                    20, 20, 20, 20, 20, 20, 20, 20, 20, 30, 30, 30, 30, 30,
                    30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
                    30, 30, 30, 30, 30, 30, 30, 30],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_min_samples_leaf': masked_array(data=[1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                    4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                    2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                    1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                    4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                    2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                    1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                    4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                    2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_min_samples_split': masked_array(data=[5, 5, 5, 10, 10, 10, 15, 15, 15, 5, 5, 5, 10, 10, 10,
                    15, 15, 15, 5, 5, 5, 10, 10, 10, 15, 15, 15, 5, 5, 5,
                    10, 10, 10, 15, 15, 15, 5, 5, 5, 10, 10, 10, 15, 15,
                    15, 5, 5, 5, 10, 10, 10, 15, 15, 15, 5, 5, 5, 10, 10,
                    10, 15, 15, 15, 5, 5, 5, 10, 10, 10, 15, 15, 15, 5, 5,
                    5, 10, 10, 10, 15, 15, 15, 5, 5, 5, 10, 10, 10, 15, 15,
                    15, 5, 5, 5, 10, 10, 10, 15, 15, 15, 5, 5, 5, 10, 10,
                    10, 15, 15, 15, 5, 5, 5, 10, 10, 10, 15, 15, 15, 5, 5,
                    5, 10, 10, 10, 15, 15, 15, 5, 5, 5, 10, 10, 10, 15, 15,
                    15, 5, 5, 5, 10, 10, 10, 15, 15, 15, 5, 5, 5, 10, 10,
                    10, 15, 15, 15, 5, 5, 5, 10, 10, 10, 15, 15, 15],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,

In [34]:
from sklearn.model_selection import RandomizedSearchCV

In [36]:
param_random = [{
    'n_estimators': [500, 1000, 1500],
    'criterion': ['entropy', 'gini'],
    'min_samples_split': [5, 10, 15],
    'min_samples_leaf': [1, 2, 4],
    'max_depth': [10, 20, 30]
}]

In [37]:
rs = RandomizedSearchCV(
    rf,
    param_random,
    scoring='accuracy',
    n_jobs=-1,
    cv=5,
    random_state=42
)

In [38]:
rs.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions=[{'criterion': ['entropy', 'gini'],
                                         'max_depth': [10, 20, 30],
                                         'min_samples_leaf': [1, 2, 4],
                                         'min_samples_split': [5, 10, 15],
                                         'n_estimators': [500, 1000, 1500]}],
                   random_state=42, scoring='accuracy')

In [39]:
rs.best_score_

np.float64(0.8625)

In [40]:
rs.best_params_

{'n_estimators': 1500,
 'min_samples_split': 10,
 'min_samples_leaf': 4,
 'max_depth': 30,
 'criterion': 'gini'}

In [41]:
rs.cv_results_

{'mean_fit_time': array([3.00368838, 2.18402915, 3.15546184, 2.08406248, 2.05681977,
        3.0296041 , 3.08549242, 1.01722531, 1.78663402, 1.01155887]),
 'std_fit_time': array([0.03053474, 0.14488994, 0.16870144, 0.10603876, 0.13411937,
        0.18019867, 0.21094018, 0.07903935, 0.01524846, 0.04600176]),
 'mean_score_time': array([0.17015572, 0.10804296, 0.14773388, 0.10078931, 0.09983387,
        0.1498332 , 0.14776473, 0.05120344, 0.05680361, 0.04345722]),
 'std_score_time': array([0.00562876, 0.01150412, 0.01095526, 0.00287389, 0.00185973,
        0.00421918, 0.00606097, 0.00300766, 0.00658735, 0.009524  ]),
 'param_n_estimators': masked_array(data=[1500, 1000, 1500, 1000, 1000, 1500, 1500, 500, 1000,
                    500],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_min_samples_split': masked_array(data=[10, 5, 10, 5, 10, 5, 5, 15, 5, 5],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_min_samples_leaf': masked_array(data=[4, 1, 4, 1, 2, 1, 4, 4, 4, 2],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_max_depth': masked_array(data=[30, 20, 20, 30, 10, 20, 10, 20, 10, 30],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'entropy', 'gini', 'entropy',
                    'gini', 'entropy', 'gini', 'gini'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'n_estimators': 1500,
   'min_samples_split': 10,
   'min_samples_leaf': 4,
   'max_depth': 30,
   'criterion': 'gini'},
  {'n_estimators': 1000,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_depth': 20,
   'criterion': 'gini'},
  {'n_estimators': 1500,
   'min_samples_split': 10,
   'min_samples_leaf': 4,
   'max_depth': 20,
   'criterion': 'gini'},
  {'n_estimators': 1000,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_depth': 30,
   'criterion': 'entropy'},
  {'n_estimators': 1000,
   'min_samples_split': 10,
   'min_samples_leaf': 2,
   'max_depth': 10,
   'criterion': 'gini'},
  {'n_estimators': 1500,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_depth': 20,
   'criterion': 'entropy'},
  {'n_estimators': 1500,
   'min_samples_split': 5,
   'min_samples_leaf': 4,
   'max_depth': 10,
   'criterion': 'gini'},
  {'n_estimators': 500,
   'min_samples_split': 15,
   'min_samples_leaf': 4,
   'max_depth': 20,
   'criterion': 'entropy'},
  {'n_estimators': 1000,
   'min_samples_split': 5,
   'min_samples_leaf': 4,
   'max_depth': 10,
   'criterion': 'gini'},
  {'n_estimators': 500,
   'min_samples_split': 5,
   'min_samples_leaf': 2,
   'max_depth': 30,
   'criterion': 'gini'}],
 'split0_test_score': array([0.8125, 0.75  , 0.8125, 0.75  , 0.8125, 0.75  , 0.8125, 0.8125,
        0.8125, 0.75  ]),
 'split1_test_score': array([0.875, 0.875, 0.875, 0.875, 0.875, 0.875, 0.875, 0.875, 0.875,
        0.875]),
 'split2_test_score': array([0.9375, 0.9375, 0.9375, 0.9375, 0.9375, 0.9375, 0.9375, 0.9375,
        0.9375, 0.9375]),
 'split3_test_score': array([0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75]),
 'split4_test_score': array([0.9375, 0.9375, 0.9375, 0.9375, 0.9375, 0.9375, 0.9375, 0.9375,
        0.9375, 0.9375]),
 'mean_test_score': array([0.8625, 0.85  , 0.8625, 0.85  , 0.8625, 0.85  , 0.8625, 0.8625,
        0.8625, 0.85  ]),
 'std_test_score': array([0.0728869 , 0.08477912, 0.0728869 , 0.08477912, 0.0728869 ,
        0.08477912, 0.0728869 , 0.0728869 , 0.0728869 , 0.08477912]),
 'rank_test_score': array([1, 7, 1, 7, 1, 7, 1, 1, 1, 7], dtype=int32)}